//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistencia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RecursosSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RecursosSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Persistencia.RecursosSQL", typeof(RecursosSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from perfiles.
        /// </summary>
        internal static string ConsultaPerfiles {
            get {
                return ResourceManager.GetString("ConsultaPerfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_consultar_usuario_login.
        /// </summary>
        internal static string consultarLogin {
            get {
                return ResourceManager.GetString("consultarLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select p.perfil,
        ///u.nombre,
        ///u.primer_apellido,
        ///u.segundo_apellido,
        ///u.correo
        /// from usuario u inner join perfiles p on
        ///u.fk_perfiles = p.id_perfil.
        /// </summary>
        internal static string ConsultaUsuarios {
            get {
                return ResourceManager.GetString("ConsultaUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_grado.
        /// </summary>
        internal static string insertar_grado {
            get {
                return ResourceManager.GetString("insertar grado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_Insertar_Alumnos.
        /// </summary>
        internal static string InsertarAlumnos {
            get {
                return ResourceManager.GetString("InsertarAlumnos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_gradoMateria.
        /// </summary>
        internal static string insertarGradoMateria {
            get {
                return ResourceManager.GetString("insertarGradoMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_grupo.
        /// </summary>
        internal static string InsertarGrupo {
            get {
                return ResourceManager.GetString("InsertarGrupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_Matricula.
        /// </summary>
        internal static string InsertarMatricula {
            get {
                return ResourceManager.GetString("InsertarMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_Nota.
        /// </summary>
        internal static string InsertarNotas {
            get {
                return ResourceManager.GetString("InsertarNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_insertar_Pago.
        /// </summary>
        internal static string InsertarPago {
            get {
                return ResourceManager.GetString("InsertarPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR_Insertar_Usuario.
        /// </summary>
        internal static string InsertaUsuarios {
            get {
                return ResourceManager.GetString("InsertaUsuarios", resourceCulture);
            }
        }
    }
}
